# Databricks notebook source
# DBTITLE 1,Create the baseline drift SQL alert
# MAGIC %md
# MAGIC # Create the baseline drift SQL alert
# MAGIC
# MAGIC This one-time setup step creates or updates a Databricks SQL Alerts V2 alert over the drift metrics table generated by `02_create_quality_monitor.py`. The alert query counts completed baseline-drift windows that exceed the thresholds in `monitor.yaml` and triggers when `breach_count > 0`.
# MAGIC
# MAGIC Set `drift_alert_warehouse_id` before running. Rerun this notebook after changing thresholds, schedules, or subscribers; the alert is updated in place by display name.

# COMMAND ----------

import sys
from pathlib import Path

MONITOR_MODULE_DIR = str(Path.cwd().resolve())
if MONITOR_MODULE_DIR not in sys.path:
    sys.path.insert(0, MONITOR_MODULE_DIR)

from monitoring_utils import (
    build_drift_breach_summary_query,
    parse_drift_detection_config,
)
from utils import config_bool, config_str, load_yaml_config

# COMMAND ----------

config_path, monitor_config = load_yaml_config("monitor.yaml", base_dir=Path.cwd())

UC_CATALOG = config_str(monitor_config, "catalog")
UC_SCHEMA = config_str(monitor_config, "schema")
UNPACKED_TABLE_NAME = config_str(monitor_config, "unpacked_table")
WAREHOUSE_ID = config_str(monitor_config, "drift_alert_warehouse_id")
ALERT_DISPLAY_NAME = config_str(monitor_config, "drift_alert_display_name")
ALERT_CRON = config_str(monitor_config, "drift_alert_quartz_cron")
ALERT_TIMEZONE = config_str(monitor_config, "drift_alert_timezone")
ALERT_NOTIFY_ON_OK = config_bool(monitor_config, "drift_alert_notify_on_ok")
ALERT_RETRIGGER_SECONDS = int(monitor_config["drift_alert_retrigger_seconds"])
DRIFT_SETTINGS = parse_drift_detection_config(monitor_config)

if ALERT_RETRIGGER_SECONDS < 0:
    raise ValueError("drift_alert_retrigger_seconds cannot be negative")


def string_list(key: str) -> list[str]:
    values = monitor_config.get(key) or []
    if not isinstance(values, list):
        raise ValueError(f"{key} must be a list")
    return [str(value).strip() for value in values if str(value).strip()]


ALERT_USER_EMAILS = string_list("drift_alert_user_emails")
ALERT_DESTINATION_IDS = string_list("drift_alert_destination_ids")
MONITORED_TABLE = f"{UC_CATALOG}.{UC_SCHEMA}.{UNPACKED_TABLE_NAME}"

print(f"Monitor config: {config_path}")
print(f"Monitored table: {MONITORED_TABLE}")
print(f"Alert: {ALERT_DISPLAY_NAME}")

# COMMAND ----------

from databricks.sdk import WorkspaceClient
from databricks.sdk.service.sql import (
    AlertEvaluationState,
    AlertLifecycleState,
    AlertV2,
    AlertV2Evaluation,
    AlertV2Notification,
    AlertV2Operand,
    AlertV2OperandColumn,
    AlertV2OperandValue,
    AlertV2Subscription,
    ComparisonOperator,
    CronSchedule,
    SchedulePauseStatus,
)

w = WorkspaceClient()
monitor_info = w.quality_monitors.get(table_name=MONITORED_TABLE)
drift_table = monitor_info.drift_metrics_table_name
if not drift_table:
    raise RuntimeError(
        f"The monitor over {MONITORED_TABLE} has no drift metrics table. Run "
        "02_create_quality_monitor.py and wait for its refresh to finish."
    )

alert_query = build_drift_breach_summary_query(drift_table, DRIFT_SETTINGS)
subscriptions = [
    AlertV2Subscription(user_email=email) for email in ALERT_USER_EMAILS
] + [
    AlertV2Subscription(destination_id=destination_id)
    for destination_id in ALERT_DESTINATION_IDS
]
notification = (
    AlertV2Notification(
        notify_on_ok=ALERT_NOTIFY_ON_OK,
        retrigger_seconds=ALERT_RETRIGGER_SECONDS,
        subscriptions=subscriptions,
    )
    if subscriptions
    else None
)

alert = AlertV2(
    display_name=ALERT_DISPLAY_NAME,
    query_text=alert_query,
    warehouse_id=WAREHOUSE_ID,
    evaluation=AlertV2Evaluation(
        source=AlertV2OperandColumn(name="breach_count"),
        comparison_operator=ComparisonOperator.GREATER_THAN,
        threshold=AlertV2Operand(
            value=AlertV2OperandValue(double_value=0.0)
        ),
        empty_result_state=AlertEvaluationState.OK,
        notification=notification,
    ),
    schedule=CronSchedule(
        quartz_cron_schedule=ALERT_CRON,
        timezone_id=ALERT_TIMEZONE,
        pause_status=SchedulePauseStatus.UNPAUSED,
    ),
    custom_summary=f"Baseline drift detected for {MONITORED_TABLE}",
    custom_description=(
        f"Queries {drift_table} using thresholds from monitor/monitor.yaml. "
        "Review the breached windows before approving model retraining."
    ),
)

# COMMAND ----------

matching_alerts = [
    existing
    for existing in w.alerts_v2.list_alerts()
    if existing.display_name == ALERT_DISPLAY_NAME
    and existing.lifecycle_state != AlertLifecycleState.DELETED
]
if len(matching_alerts) > 1:
    raise RuntimeError(
        f"Found multiple active SQL alerts named {ALERT_DISPLAY_NAME!r}; "
        "remove or rename duplicates before rerunning."
    )

if matching_alerts:
    alert_id = matching_alerts[0].id
    if not alert_id:
        raise RuntimeError("The existing SQL alert has no ID")
    configured_alert = w.alerts_v2.update_alert(
        id=alert_id,
        alert=alert,
        update_mask=(
            "display_name,query_text,warehouse_id,evaluation,schedule,"
            "custom_summary,custom_description"
        ),
    )
    action = "Updated"
else:
    configured_alert = w.alerts_v2.create_alert(alert)
    action = "Created"

print(f"{action} SQL alert {configured_alert.display_name} ({configured_alert.id})")
print(f"Drift metrics table: {drift_table}")
print(f"Schedule: {ALERT_CRON} ({ALERT_TIMEZONE})")
print(f"Subscribers: {len(subscriptions)}")
print("Alert query:")
print(alert_query)

